- name: ensure facts directory exists
  file:
    path: "/etc/ansible/facts.d"
    state: directory
    recurse: yes
    owner: "root"
    group: "root"

- name: setup custom facts
  copy:
    src: "etc/ansible/facts.d/nv_os_release.fact"
    dest: "/etc/ansible/facts.d"
    owner: "root"
    group: "root"
    mode: "0755"

- name: re-gather facts
  setup: 
    filter: ansible_local
          
- name: check distro
  fail:
    msg: "distro {{ ansible_facts['distribution'] }} not supported"
  when: ansible_facts['distribution'] != 'Ubuntu'

- name: Ubuntu pre-install tasks
  include_tasks: ubuntu-pre-install.yaml
  when: ansible_distribution == 'Ubuntu'
